### ISSUE TITLE
Menu doesn’t close after navigating to an new page

### ISSUE THREAD

**Issue by wdg** [AuroraEditor/website#12]
Menu doesn’t close after navigating to an new page

![5909ED1F-86D8-4826-A09A-AFEDFFEEA209](https://user-images.githubusercontent.com/1290461/187353384-d7201d55-427d-45f5-993e-c541e52e78f4.png)

**Comment by nanashili** [comment]
Reason for that is because of GitHub Pages.... It doesn't support the latest react tech
